#!/bin/zsh
#
# This lets you quickly jump into a modules directory.
#
# Type:
#
#   m <tab>
#
# ...to autocomplete on all of your modules in the directories specified in
# `functions/_m`. Example:
#
#    m transaction-h<tab>
#
# ...to quickly jump into transaction-html-api, for example.

cd "$MODULES/$1"
